config/routes.rb
Rails.application.routes.draw do
  root 'game#index'

  resources :memory_game

  resources :rock_paper
  
  resources :tic_tac_toe

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def index
  end
end

app/controllers/memory_game_controller.rb
class MemoryGameController < ApplicationController
  def index
  end
end

app/controllers/rock_paper_controller.rb
class RockPaperController < ApplicationController
  def index
  end
end

app/controllers/tic_tac_toe_controller.rb
class TicTacToeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/magic_8_ball_helper.rb
module Magic8BallHelper
end

app/helpers/memory_game_helper.rb
module MemoryGameHelper
end

app/helpers/rock_paper_helper.rb
module RockPaperHelper
end

app/helpers/tic_tac_toe_helper.rb
module TicTacToeHelper
end

app/views/game/index.html.erb
<div class='header'>
  <div class='center-align col s12 m2'>      
    <h1 class="z-depth-3">Games</h1>
  </div>
</div>

<div class='center-align '>
  <div >
    <a href='tic_tac_toe '><%= image_tag('tictac.jpg', class: 'pic1') %></a>
  </div>

  <div >
    <a href='rock_paper'><%= image_tag('rockpaper.jpg', class: 'pic2') %></a>
  </div>

  <div>
    <a href='memory_game'><%= image_tag('matchgame.jpg', class: 'pic3') %></a>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav>
    <div class="nav-wrapper black">
      <a href="/" class="brand-logo">Spectrum Games</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down"> 
          <li><%= link_to "Tic-Tac-Toe", tic_tac_toe_index_path %></li>
          <li><%= link_to "Rock Paper Scissors", rock_paper_index_path %></li>
          <li><%= link_to "Memory Match", memory_game_index_path %></li>
      </ul>
    </div>
  </nav>

  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JqueryGamesRails</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.1/css/materialize.min.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.1/js/materialize.min.js"></script>
</head>
<body>
<%= render 'layouts/navbar' %>
<%= yield %>

</body>
</html>

app/views/memory_game/index.html.erb
<div class='header'>
  <div class='center-align col s12 m2'>      
    <h1 class="z-depth-3">Memory Match</h1>
  </div>
</div>

<script type="text/javascript" src="memory.js"></script>
<div class="container">
      <div class="row">
        <div class="col s3 card-holder valign-wrapper">
          <h3 class="match-card one valign hide">1</h3>
        </div>
        <div class="col s3 card-holder valign-wrapper">
          <h3 class="match-card two valign hide">2</h3>
        </div>
        <div class="col s3 card-holder valign-wrapper">
          <h3 class="match-card three valign hide">3</h3>
        </div>
        <div class="col s3 card-holder valign-wrapper">
          <h3 class="match-card four valign hide">4</h3>
        </div>
      </div>
      <div class="row">
        <div class="col s3 card-holder valign-wrapper">
          <h3 class="match-card four valign hide">4</h3>
        </div>
        <div class="col s3 card-holder valign-wrapper">
          <h3 class="match-card one valign hide">1</h3>
        </div>
        <div class="col s3 card-holder valign-wrapper">
          <h3 class="match-card three valign hide">3</h3>
        </div>
        <div class="col s3 card-holder valign-wrapper">
          <h3 class="match-card two valign hide">2</h3>
        </div>
      </div>
      <div class="row">
        <div class="col s3 card-holder valign-wrapper">
          <h3 class="match-card four valign hide">4</h3>
        </div>
        <div class="col s3 card-holder valign-wrapper">
          <h3 class="match-card two valign hide">2</h3>
        </div>
        <div class="col s3 card-holder valign-wrapper">
          <h3 class="match-card one valign hide">1</h3>
        </div>
        <div class="col s3 card-holder valign-wrapper">
          <h3 class="match-card three valign hide">3</h3>
        </div>
      </div>
      <div class="row">
        <div class="col s3 card-holder valign-wrapper">
          <h3 class="match-card two valign hide">2</h3>
        </div>
        <div class="col s3 card-holder valign-wrapper">
          <h3 class="match-card four valign hide">4</h3>
        </div>
        <div class="col s3 card-holder valign-wrapper">
          <h3 class="match-card one valign hide">1</h3>
        </div>
        <div class="col s3 card-holder valign-wrapper">
          <h3 class="match-card three valign hide">3</h3>
        </div>
      </div>
    </div>

app/views/rock_paper/index.html.erb
<div class='header'>
  <div class='center-align col s12 m2'>      
    <h1 class="z-depth-3">Rock Paper Scissors</h1>
  </div>
</div>

<div id='direction'>
  <h3> Typical Rock Paper Scissors game, click an image to play</h3>
</div>

<div class='center-align responsive-img'>
  <div class='player_choice'>
    <%= image_tag('rock.jpg', class: 'rock', id:'rock') %>
  </div>

  <div class='player_choice'>
    <%= image_tag('paper.jpg', class: 'paper', id:'paper') %>
  </div>

  <div class='player_choice'>
    <%= image_tag('scissors.jpg', class: 'scissors', id:'scissors') %>
  </div>
</div>

  <div id='para'>
    <h3 id='comp_choice'> </h3>
    <h3 id='winner'> </h3>
  </div>


    

app/views/tic_tac_toe/index.html.erb
<div class='header'>
  <div class='center-align col s12 m2'>      
    <h1 class="z-depth-3">Tic-Tac-Toe</h1>
  </div>
</div>

<div class="container">
      <div class="row">
        <div class="col s3 tic_tac valign-wrapper">
        
        </div>
        <div class="col s3 tic_tac valign-wrapper">
        
        </div>
        <div class="col s3 tic_tac valign-wrapper">
          
        </div>
      </div>  
      <div class="row">
        <div class="col s3 tic_tac valign-wrapper">
         
        </div>
        <div class="col s3 tic_tac valign-wrapper">
         
        </div>
        <div class="col s3 tic_tac valign-wrapper">
        
        </div>
      </div>
      <div class="row">
        <div class="col s3 tic_tac valign-wrapper">
         
        </div>
        <div class="col s3 tic_tac valign-wrapper">
          
        </div>
        <div class="col s3 tic_tac valign-wrapper">
        
        </div>
      </div>
</div>